- name: restart buildmaster
  service: name=buildmaster state=restarted
  notify: restart buildslave

- name: restart buildslave
  service: name=buildslave state=restarted

- name: restart nginx
  service: name=nginx state=restarted
